export type Language = {
  code: string;
  name: string;
};

const languages = [
  { name: 'afar', code: 'aa' },
  { name: 'abkhazian', code: 'ab' },
  { name: 'afrikaans', code: 'af' },
  { name: 'akan', code: 'ak' },
  { name: 'albanian', code: 'sq' },
  { name: 'amharic', code: 'am' },
  { name: 'arabic', code: 'ar' },
  { name: 'aragonese', code: 'an' },
  { name: 'armenian', code: 'hy' },
  { name: 'assamese', code: 'as' },
  { name: 'avaric', code: 'av' },
  { name: 'avestan', code: 'ae' },
  { name: 'aymara', code: 'ay' },
  { name: 'azerbaijani', code: 'az' },
  { name: 'bashkir', code: 'ba' },
  { name: 'bambara', code: 'bm' },
  { name: 'basque', code: 'eu' },
  { name: 'belarusian', code: 'be' },
  { name: 'bengali', code: 'bn' },
  { name: 'bihari languages', code: 'bh' },
  { name: 'bislama', code: 'bi' },
  { name: 'tibetan', code: 'bo' },
  { name: 'bosnian', code: 'bs' },
  { name: 'breton', code: 'br' },
  { name: 'bulgarian', code: 'bg' },
  { name: 'burmese', code: 'my' },
  { name: 'catalan', code: 'ca' },
  { name: 'valencian', code: 'ca' },
  { name: 'czech', code: 'cs' },
  { name: 'chamorro', code: 'ch' },
  { name: 'chechen', code: 'ce' },
  { name: 'chinese', code: 'zh' },
  { name: 'church slavic', code: 'cu' },
  { name: 'old slavonic', code: 'cu' },
  { name: 'church slavonic', code: 'cu' },
  { name: 'old bulgarian', code: 'cu' },
  { name: 'old church slavonic', code: 'cu' },
  { name: 'chuvash', code: 'cv' },
  { name: 'cornish', code: 'kw' },
  { name: 'corsican', code: 'co' },
  { name: 'cree', code: 'cr' },
  { name: 'welsh', code: 'cy' },
  { name: 'danish', code: 'da' },
  { name: 'german', code: 'de' },
  { name: 'divehi', code: 'dv' },
  { name: 'dhivehi', code: 'dv' },
  { name: 'maldivian', code: 'dv' },
  { name: 'dutch', code: 'nl' },
  { name: 'flemish', code: 'nl' },
  { name: 'dzongkha', code: 'dz' },
  { name: 'greek', code: 'el' },
  { name: 'english', code: 'en' },
  { name: 'esperanto', code: 'eo' },
  { name: 'estonian', code: 'et' },
  { name: 'ewe', code: 'ee' },
  { name: 'faroese', code: 'fo' },
  { name: 'persian', code: 'fa' },
  { name: 'fijian', code: 'fj' },
  { name: 'finnish', code: 'fi' },
  { name: 'french', code: 'fr' },
  { name: 'western frisian', code: 'fy' },
  { name: 'fulah', code: 'ff' },
  { name: 'georgian', code: 'ka' },
  { name: 'gaelic', code: 'gd' },
  { name: 'scottish gaelic', code: 'gd' },
  { name: 'irish', code: 'ga' },
  { name: 'galician', code: 'gl' },
  { name: 'manx', code: 'gv' },
  { name: 'guarani', code: 'gn' },
  { name: 'gujarati', code: 'gu' },
  { name: 'haitian', code: 'ht' },
  { name: 'haitian creole', code: 'ht' },
  { name: 'hausa', code: 'ha' },
  { name: 'hebrew', code: 'he' },
  { name: 'herero', code: 'hz' },
  { name: 'hindi', code: 'hi' },
  { name: 'hiri motu', code: 'ho' },
  { name: 'croatian', code: 'hr' },
  { name: 'hungarian', code: 'hu' },
  { name: 'igbo', code: 'ig' },
  { name: 'icelandic', code: 'is' },
  { name: 'ido', code: 'io' },
  { name: 'sichuan yi', code: 'ii' },
  { name: 'nuosu', code: 'ii' },
  { name: 'inuktitut', code: 'iu' },
  { name: 'interlingue', code: 'ie' },
  { name: 'occidental', code: 'ie' },
  { name: 'interlingua', code: 'ia' },
  { name: 'indonesian', code: 'id' },
  { name: 'inupiaq', code: 'ik' },
  { name: 'italian', code: 'it' },
  { name: 'javanese', code: 'jv' },
  { name: 'japanese', code: 'ja' },
  { name: 'kalaallisut', code: 'kl' },
  { name: 'greenlandic', code: 'kl' },
  { name: 'kannada', code: 'kn' },
  { name: 'kashmiri', code: 'ks' },
  { name: 'kanuri', code: 'kr' },
  { name: 'kazakh', code: 'kk' },
  { name: 'central khmer', code: 'km' },
  { name: 'kikuyu', code: 'ki' },
  { name: 'gikuyu', code: 'ki' },
  { name: 'kinyarwanda', code: 'rw' },
  { name: 'kirghiz', code: 'ky' },
  { name: 'kyrgyz', code: 'ky' },
  { name: 'komi', code: 'kv' },
  { name: 'kongo', code: 'kg' },
  { name: 'korean', code: 'ko' },
  { name: 'kuanyama', code: 'kj' },
  { name: 'kwanyama', code: 'kj' },
  { name: 'kurdish', code: 'ku' },
  { name: 'lao', code: 'lo' },
  { name: 'latin', code: 'la' },
  { name: 'latvian', code: 'lv' },
  { name: 'limburgan', code: 'li' },
  { name: 'limburger', code: 'li' },
  { name: 'limburgish', code: 'li' },
  { name: 'lingala', code: 'ln' },
  { name: 'lithuanian', code: 'lt' },
  { name: 'luxembourgish', code: 'lb' },
  { name: 'letzeburgesch', code: 'lb' },
  { name: 'luba-katanga', code: 'lu' },
  { name: 'ganda', code: 'lg' },
  { name: 'macedonian', code: 'mk' },
  { name: 'marshallese', code: 'mh' },
  { name: 'malayalam', code: 'ml' },
  { name: 'maori', code: 'mi' },
  { name: 'marathi', code: 'mr' },
  { name: 'malay', code: 'ms' },
  { name: 'malagasy', code: 'mg' },
  { name: 'maltese', code: 'mt' },
  { name: 'mongolian', code: 'mn' },
  { name: 'nauru', code: 'na' },
  { name: 'navajo', code: 'nv' },
  { name: 'navaho', code: 'nv' },
  { name: 'ndebele, south', code: 'nr' },
  { name: 'south ndebele', code: 'nr' },
  { name: 'ndebele, north', code: 'nd' },
  { name: 'north ndebele', code: 'nd' },
  { name: 'ndonga', code: 'ng' },
  { name: 'nepali', code: 'ne' },
  { name: 'norwegian', code: 'no' },
  { name: 'chichewa', code: 'ny' },
  { name: 'chewa', code: 'ny' },
  { name: 'nyanja', code: 'ny' },
  { name: 'occitan', code: 'oc' },
  { name: 'ojibwa', code: 'oj' },
  { name: 'oriya', code: 'or' },
  { name: 'oromo', code: 'om' },
  { name: 'ossetian', code: 'os' },
  { name: 'ossetic', code: 'os' },
  { name: 'panjabi', code: 'pa' },
  { name: 'punjabi', code: 'pa' },
  { name: 'pali', code: 'pi' },
  { name: 'polish', code: 'pl' },
  { name: 'portuguese', code: 'pt' },
  { name: 'pushto', code: 'ps' },
  { name: 'pashto', code: 'ps' },
  { name: 'quechua', code: 'qu' },
  { name: 'romansh', code: 'rm' },
  { name: 'romanian', code: 'ro' },
  { name: 'moldavian', code: 'ro' },
  { name: 'moldovan', code: 'ro' },
  { name: 'russian', code: 'ru' },
  { name: 'sango', code: 'sg' },
  { name: 'sinhala', code: 'si' },
  { name: 'sinhalese', code: 'si' },
  { name: 'slovak', code: 'sk' },
  { name: 'slovenian', code: 'sl' },
  { name: 'northern sami', code: 'se' },
  { name: 'samoan', code: 'sm' },
  { name: 'shona', code: 'sn' },
  { name: 'sindhi', code: 'sd' },
  { name: 'somali', code: 'so' },
  { name: 'sotho, southern', code: 'st' },
  { name: 'spanish', code: 'es' },
  { name: 'castilian', code: 'es' },
  { name: 'sardinian', code: 'sc' },
  { name: 'serbian', code: 'sr' },
  { name: 'swati', code: 'ss' },
  { name: 'sundanese', code: 'su' },
  { name: 'swahili', code: 'sw' },
  { name: 'swedish', code: 'sv' },
  { name: 'tahitian', code: 'ty' },
  { name: 'tamil', code: 'ta' },
  { name: 'tatar', code: 'tt' },
  { name: 'telugu', code: 'te' },
  { name: 'tajik', code: 'tg' },
  { name: 'tagalog', code: 'tl' },
  { name: 'thai', code: 'th' },
  { name: 'tigrinya', code: 'ti' },
  { name: 'tonga', code: 'to' },
  { name: 'tswana', code: 'tn' },
  { name: 'tsonga', code: 'ts' },
  { name: 'turkmen', code: 'tk' },
  { name: 'turkish', code: 'tr' },
  { name: 'twi', code: 'tw' },
  { name: 'uighur', code: 'ug' },
  { name: 'uyghur', code: 'ug' },
  { name: 'ukrainian', code: 'uk' },
  { name: 'urdu', code: 'ur' },
  { name: 'uzbek', code: 'uz' },
  { name: 'venda', code: 've' },
  { name: 'vietnamese', code: 'vi' },
  { name: 'volapük', code: 'vo' },
  { name: 'walloon', code: 'wa' },
  { name: 'wolof', code: 'wo' },
  { name: 'xhosa', code: 'xh' },
  { name: 'yiddish', code: 'yi' },
  { name: 'yoruba', code: 'yo' },
  { name: 'zhuang', code: 'za' },
  { name: 'chuang', code: 'za' },
  { name: 'zulu', code: 'zu' },
];

export { languages };
